#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "This script must be run as root!"
  exit
fi

DIALOG_TITLE="HTTPS Setup"

install() {
    [ -e /etc/lsb-release ] && ubuntu_install

}

setup_certbot() {
    STEP=certbot
    certbot --nginx --email "$EMAIL" -d "$DOMAIN" || die certbotsetup

    # install crontab if not already installed
    crontab -l | grep -q "15 02 * * * `which certbot` renew" || autorenew_crontab
}

autorenew_crontab() {
    (crontab -l 2>/dev/null; echo "15 02 * * * `which certbot` renew --pre-hook \"service nginx stop\" --post-hook \"service nginx start\"") | crontab -
}

ubuntu_install() {
    OS=ubuntu

    # install whiptail if not present
    [ `dpkg -l | grep '\snginx\s\s' | wc -l` -eq 1 ] || apt-get install whiptail

    EMAIL=$(whiptail --inputbox "Enter your email (used by certbot for urgent renewal and security notices)" 8 78 --title "$DIALOG_TITLE" 3>&1 1>&2 2>&3)

    if [ $? -ne 0 ]; then
        whiptail --title "$DIALOG_TITLE" --msgbox "You must provide an email!" 8 78
        exit
    fi

    DOMAIN=$(whiptail --inputbox 'Enter your domain (NOT IP!) that points to this IP (comma separated)' 8 78 --title "$DIALOG_TITLE" 3>&1 1>&2 2>&3)

    if [ $? -ne 0 ]; then
        whiptail --title "$DIALOG_TITLE" --msgbox "You must provide domain(s)!" 8 78
        exit
    fi

    ubuntu_install_nginx
    ubuntu_install_certbot
    setup_certbot
    echo "HTTPS set up successfully!"
    exit
}

ubuntu_install_nginx() {
    STEP=inginx
    [ `dpkg -l | grep '\snginx\s\s' | wc -l` -eq 1 ] && return

    add-apt-repository "deb http://nginx.org/packages/ubuntu/ $(lsb_release -s -c) main" -y || die addrepo
    apt-get update || die aptupdate
    apt-get install nginx -y || die install

    sed "s/SERVERNAME/$DOMAIN/" < nginx.conf > /etc/nginx/sites-enabled/default
}

ubuntu_install_certbot() {
    step=icertbot
    [ `dpkg -l | grep '\spython-certbot-nginx\s\s' | wc -l` -eq 1 ] && return

    apt-get install software-properties-common -y || die software-properties-common
    add-apt-repository ppa:certbot/certbot -y || die ppa
    apt-get update || die aptupdate
    apt-get install python-certbot-nginx -y || die install
}


die() {
    echo "!!! SOMETHING WENT WRONG ($OS $STEP $1) !!!"
    exit
}

install
